baseURL = "https://amemorieren.github.io/"
languageCode = "zh-tw"
title = "Blog"
theme = "PaperMod"

enableRobotsTXT = true
enableEmoji = true
hasCJKLanguage = true

pagination.pagerSize = 10

[params]
  env = "production"
  title = "Blog"
  description = ""
  author = "Eren"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  disableSpecial1stPost = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "關於我"
    url = "/about/"
    weight = 20

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
